### ISSUE TITLE
Failed to deconstruct when using record with inheritence

### ISSUE THREAD

**Issue by fakhrulhilal** [evjenio/masking.serilog#5]
# Synopsis

The masking serilog failed to deconstruct an instance of record which inheriting from another record. Any code calling [`ILogger`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.ilogger-1) interface will make the program stops working completely. Below is the debug messaging log:
```
2021-05-11T09:06:59.7952117Z The property accessor System.Reflection.GenericParameterAttributes GenericParameterAttributes threw exception System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Method may only be called on a Type for which Type.IsGenericParameter is true.
   at System.RuntimeType.get_GenericParameterAttributes()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Reflection.PropertyInfo.GetValue(Object obj)
   at Masking.Serilog.ByMasking.DestructureByMaskingPolicy.SafeGetPropertyValue(Object o, PropertyInfo pi)
2021-05-11T09:06:59.7975937Z Maximum destructuring depth reached.
```
Tech detail:
- dotnet 5
- Masking.Serilog 1.0.13

## Example code
```cs
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;
using Masking.Serilog;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Serilog;

Host.CreateDefaultBuilder(args)
    .ConfigureLogging((context, logBuilder) =>
    {
        var logConfig = new LoggerConfiguration()
            .Enrich.FromLogContext()
            .ReadFrom.Configuration(context.Configuration)
            .WriteTo.Console()
            .Destructure.ByMaskingProperties(opt =>
            {
                opt.PropertyNames.Add(nameof(MailConfig.Password));
                opt.Mask = "***";
                opt.ExcludeStaticProperties = true;
            });
        var logger = logConfig.CreateLogger();
        logBuilder.ClearProviders().AddSerilog(logger);
    })
    .ConfigureServices(services => services.AddHostedService<Dummy>())
    .Build().Run();

class Dummy : IHostedService
{
    private readonly ILogger<Dummy> _log;
    public Dummy(ILogger<Dummy> log) => _log = log;

    public Task StartAsync(CancellationToken cancellationToken)
    {
        // enable for error tracing
        Serilog.Debugging.SelfLog.Enable(msg => Debug.WriteLine(msg));
        var config = new MailConfig
        {
            Username = "user",
            Password = "secret",
            ServerAddress = "localhost",
            Port = 25,
            UseSecureMode = false
        };
        _log.LogInformation("Dumping my {@Config}", config);
        return Task.CompletedTask;
    }

    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;
}

record ConnectionConfig
{
    public int Port { get; set; }
    public bool UseSecureMode { get; set; }
}

record MailConfig : ConnectionConfig
{
    public string Username { get; set; } = string.Empty;
    public string Password { get; set; } = string.Empty;
    public string ServerAddress { get; set; } = string.Empty;
}
```

## Workaround

Use ordinal class instead, change `ConnectionConfig` and `MailConfig` to use `class` instead of `record`.

**Comment by kidchenko-jq-tw** [comment]
+1 have the same problem.

**Comment by zachrybaker** [comment]
I can create this issue without use of record.

**Comment by fakhrulhilal** [comment]
No update from the author, instead, I'm making [my own lib](https://github.com/fakhrulhilal/serilog.customdestructurepolicy)
